name: Deploy Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Print TODO
        run: |
            echo "TODO: deploy-backend"
